# Generated by Django 4.0.6 on 2022-08-02 19:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('collection_frequency', models.IntegerField()),
                ('last_collection', models.DateTimeField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howmanytimes.operation')),
            ],
        ),
    ]
