# Generated by Django 4.0.6 on 2022-08-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howmanytimes', '0002_alter_bin_last_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='last_collection',
            field=models.DateTimeField(),
        ),
    ]
